version: "3"

services:
  master:
    image: bitnami/redis:5.0-debian-9
    environment:
      REDIS_REPLICATION_MODE: master
      ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      - redis_network
    restart: always

  slave-1:
    image: bitnami/redis:5.0-debian-9
    environment:
      REDIS_REPLICATION_MODE: slave
      REDIS_MASTER_HOST: master
      ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      - redis_network

  slave-2:
    image: bitnami/redis:5.0-debian-9
    environment:
      REDIS_REPLICATION_MODE: slave
      REDIS_MASTER_HOST: master
      ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      - redis_network

  slave-3:
    image: bitnami/redis:5.0-debian-9
    environment:
      REDIS_REPLICATION_MODE: slave
      REDIS_MASTER_HOST: master
      ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      - redis_network

  sentinel-1:
    image: bitnami/redis-sentinel:5.0-debian-9
    environment:
      REDIS_MASTER_HOST: master
      REDIS_SENTINEL_DOWN_AFTER_MILLISECONDS: 5000
      REDIS_SENTINEL_FAILOVER_TIMEOUT: 5000
    networks:
      - redis_network

  sentinel-2:
    image: bitnami/redis-sentinel:5.0-debian-9
    environment:
      REDIS_MASTER_HOST: master
      REDIS_SENTINEL_DOWN_AFTER_MILLISECONDS: 5000
      REDIS_SENTINEL_FAILOVER_TIMEOUT: 5000
    networks:
      - redis_network

  sentinel-3:
    image: bitnami/redis-sentinel:5.0-debian-9
    environment:
      REDIS_MASTER_HOST: master
      REDIS_SENTINEL_DOWN_AFTER_MILLISECONDS: 5000
      REDIS_SENTINEL_FAILOVER_TIMEOUT: 5000
    networks:
      - redis_network

  haprxoy:
    image: rafpe/docker-haproxy-rsyslog
    ports:
      - 80:80
      - 5000-5001:5000-5001
    volumes:
      - ${PWD}/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    networks:
      - redis_network

networks:
  redis_network:
    driver: bridge
